#!/bin/bash

set -e

git config user.email "jenkins@demo.com"
git config user.name "jenkins-bot"

git fetch origin

echo "Comparing files..."

BASE_HASH=$(git rev-parse origin/BASE:releasefile/user_stories.txt || echo "none")
SIT_HASH=$(git rev-parse origin/SITFULL:releasefile/user_stories.txt || echo "none")

if [ "$BASE_HASH" = "$SIT_HASH" ]; then
    echo "Same → clean BOTH"

    git checkout BASE
    rm -rf releasefile/*
    git add .
    git commit -m "cleanup BASE" || true
    git push origin BASE

    git checkout SITFULL
    rm -rf releasefile/*
    git add .
    git commit -m "cleanup SITFULL" || true
    git push origin SITFULL

else
    echo "Different → clean only SITFULL"

    git checkout SITFULL
    rm -rf releasefile/*
    git add .
    git commit -m "cleanup SITFULL only" || true
    git push origin SITFULL
fi
